config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'home', to: "pages#home"
  get 'faq', to: 'pages#faq'
  get 'documentation', to: 'pages#documentation'
  root 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def faq
    end

    def documentation
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <div class="content">
      <%= render "shared/header" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/documentation.html.erb
<% content_for :title, "Documentation | DrugDiscovery@TACC" %>

<div id="documentation">

    <h1>Tutorial</h1>
    <h3>Account Creation & Finding the Application</h3>
    <ol>
        <li>Visit the <%= link_to "TACC portal account request page",  "https://portal.tacc.utexas.edu/account-request" %> to request an account.</li>
        <li>Once approved, login to the <%= link_to "UTRC Portal", "https://utrc.tacc.utexas.edu" %>.</li>
        <li>Navigate to Applications -> Simulation -> AutoDock Vina v1.2.3.</li>
    </ol>

    <h3>Submitting a Job</h3>
    <div class="tutorial-item">
        <%= image_tag "tutorial/input_receptor.png", :class => 'tutorial-img' %>
        <div>First upload a .pdb or .pdbqt protein receptor file to your TACC storage system work directory from the "Data Files" tab. Then, select the protein file in this box.</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/input_library.png", :class => 'tutorial-img' %>
        <div>Choose a ligand library from the drop down list. Use the "Test-set" library first to make sure your job is working with the inputs as expected before proceeding to the larger libraries. More information on each library can be found in our <%= link_to "FAQ", faq_path %>.</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/input_center.png", :class => 'tutorial-img' %>
        <div>Specify the X-Y-Z coordinate grid-center for the search area. This must be located inside of the uploaded protein receptor. Units are in Angstroms. Use comma-separated values with no spaces in between.</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/input_box.png", :class => 'tutorial-img' %>
        <div>Specify the search area box's X-Y-Z bounds. Units are in Angstroms. Use comma-separated values with no spaces in between. NOTE: The larger the box size, the longer the job will take to run - be conservative with box size.</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/input_returned_scores.png", :class => 'tutorial-img' %>
        <div>Choose how many of the top scoring molecules to be returned (maximum: 1000).</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/config_queue.png", :class => 'tutorial-img' %>
        <div>Choose the Lonestar6 compute queue to run your job on. Recommended "development" for the Test-set library and "normal" for all other libraries.</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/config_runtime.png", :class => 'tutorial-img' %>
        <div>Specify the maximum runtime. Try to choose a time that will allow enough time for the job to finish, with a little extra on top. If your job does not finish by this time, it will exit and no results will be returned. However, a higher maximum runtime may cause your job to wait longer in the queue. Suggested runtimes:
        <table>
            <tr>
                <th>Ligand Library</th>
                <th>Suggested Max Runtime</th>
            </tr>
            <tr>
                <td>Test-set</td>
                <td class='center'>10 minutes</td>
            </tr>
            <tr>
                <td>ZINC-in-trials</td>
                <td class='center'>4 hours</td>
            </tr>
            <tr>
                <td>ZINC-fragments</td>
                <td class='center'>15 hours</td>
            </tr>
            <tr>
                <td>Enamine-PC</td>
                <td class='center'>8 hours</td>
            </tr>
            <tr>
                <td>Enamine-AC</td>
                <td class='center'>26 hours</td>
            </tr>
            <tr>
                <td>Enamine-HTSC</td>
                <td class='center'>26 hours</td>
            </tr>
        </table>
        <p>Note that these suggested times give a ~2 hour buffer on top of our internal benchmark times for each library and using a 22x22x22 Angstrom box. Given different input parameters (especially box size), these times may need to be significantly adjusted for your job.</div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/config_nodes.png", :class => 'tutorial-img' %>
        <div>Input the exact number of processors and nodes required, depending on the ligand library. You must input based on the table below, or your job will fail. Note that Processors on Each Node is always set to 32.
        <table>
            <tr>
                <th>Ligand Library</th>
                <th>Processors on Each Node</th>
                <th>Node Count</th>
            </tr>
            <tr>
                <td>ZINC-in-trials</td>
                <td class='center'>32</td>
                <td class='center'>1</td>
            </tr>
            <tr>
                <td>ZINC-fragments</td>
                <td class='center'>32</td>
                <td class='center'>1</td>
            </tr>
            <tr>
                <td>Enamine-PC</td>
                <td class='center'>32</td>
                <td class='center'>1</td>
            </tr>
            <tr>
                <td>Enamine-AC</td>
                <td class='center'>32</td>
                <td class='center'>3</td>
            </tr>
            <tr>
                <td>Enamine-HTSC</td>
                <td class='center'>32</td>
                <td class='center'>10</td>
            </tr>
        </table>
        </div>
    </div>
    <hr>
    <div class="tutorial-item">
        <%= image_tag "tutorial/submit.png", :class => 'tutorial-img' %>
        <div>Default values can be used in the other boxes. Press the "Submit" button when ready.</div>
    </div>
    <hr>

    <h3>How do I monitor my job's status?</h3>
    <p>Navigate to the UTRC Portal -> Log in -> History</p>

    <h3>How do I retrieve my job's output?</h3>
    <p>There are two ways:</p>
    <ol>
        <li>Navigate to the UTRC Portal -> Log in -> History -> Select the link for your job under the Output Location column.
        <li>Navigate to the Output Location on your TACC Storage System that you specified when submitting the job.
    </ol>

    <h3>How do I view my results interactively?</h3>
    <p>The user may also choose to visualize their resulting output file utilizing the <%= link_to "ChimeraX application", "https://github.com/tiffanyhuff/ChimeraXApp" %> on TACC's Lonestar6 supercomputer. To run the application, the user must submit a job using the <%= link_to "University of Texas Research Cyberinfrastructure (UTRC) system", "https://utrc.tacc.utexas.edu/" %>. A virtual DCV session will be initialized for the user, and a document titled 'ChimeraX_dcvserver.txt' will be created in the user's work folder with connection instructions. Once connected, the <%= link_to "University of California San Francisco (UCSF)", "https://www.ucsf.edu/" %> <%= link_to "ChimeraX", "https://www.cgl.ucsf.edu/chimerax/" %> software will begin running, and a Tapis jobs archive folder will be created on the desktop for the user's convenience. The user may then use the ChimeraX program to open the file containing the top scoring docked ligands.</p>
    <div class='spacing'></div>
</div>

app/views/pages/home.html.erb
<% content_for :title, "Home | DrugDiscovery@TACC" %>

<div class="jumbotron">
    <!-- <div class="center-block collapse"><img src="images/Design-safe-logo-4.jpg" class="center-block" style="max-width: 50%;"></img></div> -->
    <h2>Thank you for visiting the Virtual Drug Discovery Portal!</h2>
    <p class="lead">
        This application has been re-written, expanded with new features, and moved to our <a href="https://utrc.tacc.utexas.edu/workbench">UTRC Web Portal</a>. It can be found under Applications -> Simulation -> AutoDock Vina v1.2.3.
    </p>
</div>

<div class="home-contents">
    <div class="center-block collapse"><%= image_tag "1cip_white_artistically_compromised.jpg" %></div>
    <div class="about">
        <h3>About Drug Discovery @TACC</h3>
        <p>The original idea for this site was from the existing docking portal run at UTMB, Docking At UTMB. In order to scale the size of the docking computations, the portal was rewritten to work with TACC's infrastructure. A collaboration was launched between UTMB and TACC to build the portal infrastructure and docking execution pipeline to run on TACC's high performance computing computational resources. Today, the project continues to expand in technical capability and offerings while supporting an ever-growing community.</p>
        <p><strong>Contributors:</strong><br>
            Dr. Stan Watowich (UTMB)<br>
            Usha Viswanathan (UTMB)<br>
            Stephen Mock (TACC)<br>
            John Fonner (TACC)<br>
            Joe Allen (TACC)<br>
            Sal Tijerina (TACC)<br>
            Suman Sirimulla (UTEP)<br>
            Erik Ferlanti (TACC)<br>
            Austin Darrow (TACC)<br>
            Tiffany Huff (TACC)<br>
            Joshua Medina (TACC)<br>
            Joshua Urrutia (TACC)<br>
            Braulio Lopez (TACC)<br>
        </p>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8 text-right-lg "> <p> ©2023 <%= link_to "Texas Advanced Computing Center", 'https://www.tacc.utexas.edu' %></p> </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="banner">
    <div class="logo pull-left"><%= image_tag "logo.svg" %></div>
    <hgroup class="wordmark">
        <h1>Drug Discovery @ TEXAS ADVANCED COMPUTING CENTER</h1>
        <h2>Powering Discoveries That Change The World</h2>
    </hgroup>
    <div class="logo pull-right"><%= image_tag "ut.png", style: "width='120' height='52' alt='UT Logo'" %></div>
</header>

<nav class="navbar">
    <div class="container">
        <div id="navbar">
        <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Documentation", documentation_path %></li>
            <li><%= link_to "FAQ", faq_path %></li>
        </ul>
        </div>
    </div>
</nav>